global:
  scrape_interval: 10s  # By default, scrape targets every 10 seconds.
  

scrape_configs:
  - job_name: "url_shortener"
    metrics_path: /metrics   # PrometheusMetrics exposes metrics here by default
    static_configs:
      - targets: ["client:80"]   # replace with your Flask host:port
  
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]  # Node Exporter default port is 9100
    metrics_path: /metrics   # PrometheusMetrics exposes metrics here by default

