
# -------------------------------
# MongoDB (StatefulSet)
# -------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-ss
  namespace: url-shortener
spec:
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ss-pod
  template:
    metadata:
      labels:
        app: mongo-ss-pod
    spec:
      containers:
        - name: mongodb
          image: mongo:noble
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: kaap
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: kaap
          volumeMounts:
            - name: mongo-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["mongod", "--bind_ip_all"]
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

--- 

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: mongo-ss-pod
  ports:
    - port: 27017
      targetPort: 27017
